// FindMyAI — base de connaissances
// Chaque outil :
//  price: 'free' | 'freemium' | 'cheap'
//  flags: ensemble de drapeaux pour filtrer
//    - 'private'  : on-device / open-source / pas d'entraînement sur vos données
//    - 'eu'       : entreprise ou hébergement européen (RGPD)
//    - 'offline'  : peut tourner sans Internet
//    - 'hidden'   : alternative peu connue (pas ChatGPT/Gemini/Copilot)
//  jobs: liste de métiers concernés
//  why : pourquoi on le recommande pour ce profil
//  security: score de sécurité 1–5 (voir SECURITY_RUBRIC dans app.js)
//  secNote : justification courte du score

window.JOBS = [
  { id: "dev",        label: "Développeur·euse" },
  { id: "design",     label: "Designer / Graphiste" },
  { id: "writer",     label: "Rédacteur·trice / Journaliste" },
  { id: "teacher",    label: "Enseignant·e" },
  { id: "student",    label: "Étudiant·e" },
  { id: "researcher", label: "Chercheur·euse" },
  { id: "marketer",   label: "Marketing / Communication" },
  { id: "translator", label: "Traducteur·trice" },
  { id: "lawyer",     label: "Juriste / Avocat·e" },
  { id: "doctor",     label: "Santé / Médecine" },
  { id: "finance",    label: "Comptable / Finance" },
  { id: "sales",      label: "Commercial·e" },
  { id: "support",    label: "Service client" },
  { id: "video",      label: "Vidéaste / Monteur·euse" },
  { id: "photo",      label: "Photographe" },
  { id: "music",      label: "Musicien·ne" },
  { id: "hr",         label: "RH / Recrutement" },
  { id: "pm",         label: "Chef·fe de projet" },
  { id: "data",       label: "Analyste de données" },
  { id: "artisan",    label: "Artisan / TPE" },
];

window.TOOLS = [
  // ---------- Polyvalents ----------
  {
    name: "Le Chat (Mistral)",
    url: "https://chat.mistral.ai",
    price: "freemium",
    flags: ["eu", "hidden"],
    jobs: ["writer", "marketer", "teacher", "student", "lawyer", "hr", "support", "sales", "pm", "finance", "artisan"],
    why: "Assistant français, hébergé en Europe, gratuit et rapide.",
    security: 4,
    secNote: "Hébergement UE, modèles à poids ouverts, pas d'entraînement sur vos prompts par défaut.",
  },
  {
    name: "HuggingChat",
    url: "https://huggingface.co/chat",
    price: "free",
    flags: ["private", "hidden"],
    jobs: ["writer", "student", "teacher", "researcher", "marketer", "support", "hr", "pm"],
    why: "Modèles open-source, sans collecte abusive, plusieurs IA au choix.",
    security: 4,
    secNote: "Modèles open-source, conversations non utilisées pour l'entraînement.",
  },
  {
    name: "Perplexity",
    url: "https://www.perplexity.ai",
    price: "freemium",
    jobs: ["researcher", "student", "marketer", "sales", "pm", "writer"],
    why: "Réponses sourcées avec citations — idéal pour vérifier l'info.",
    security: 3,
    secNote: "Politique claire, opt-out d'entraînement disponible — hébergé US.",
  },
  {
    name: "Ollama (local)",
    url: "https://ollama.com",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["dev", "researcher", "writer", "lawyer", "doctor", "finance"],
    why: "Tourne 100 % en local sur votre machine — vos données ne sortent jamais.",
    security: 5,
    secNote: "100 % local, code open-source, aucune télémétrie réseau requise.",
  },
  {
    name: "NotebookLM",
    url: "https://notebooklm.google",
    price: "free",
    jobs: ["student", "teacher", "researcher", "lawyer", "writer", "pm"],
    why: "Téléchargez vos PDF/notes, l'IA répond en citant vos documents.",
    security: 3,
    secNote: "Google s'engage à ne pas entraîner sur vos documents — mais hébergé US.",
  },

  // ---------- Développement ----------
  {
    name: "Codeium",
    url: "https://codeium.com",
    price: "free",
    jobs: ["dev"],
    why: "Auto-complétion gratuite illimitée pour tous les IDE.",
    security: 3,
    secNote: "Pas d'entraînement sur le code des comptes gratuits, mais service hébergé.",
  },
  {
    name: "Continue.dev",
    url: "https://continue.dev",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["dev"],
    why: "Extension VS Code open-source, branchable sur un modèle local.",
    security: 5,
    secNote: "Open-source, peut être branché sur Ollama pour rester 100 % local.",
  },
  {
    name: "Tabby",
    url: "https://tabby.tabbyml.com",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["dev"],
    why: "Copilote auto-hébergeable — souverain et gratuit.",
    security: 5,
    secNote: "Open-source, auto-hébergé : votre code ne quitte jamais votre serveur.",
  },
  {
    name: "Phind",
    url: "https://www.phind.com",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["dev"],
    why: "Moteur de recherche dédié au code, avec sources.",
    security: 3,
    secNote: "Hébergé US, politique standard — réponses sourcées vérifiables.",
  },
  {
    name: "Cursor",
    url: "https://cursor.com",
    price: "freemium",
    jobs: ["dev"],
    why: "Éditeur basé VS Code avec IA intégrée — palier gratuit utile.",
    security: 3,
    secNote: "Mode Privacy disponible (aucun stockage), mais désactivé par défaut.",
  },

  // ---------- Design / Image ----------
  {
    name: "Krea",
    url: "https://www.krea.ai",
    price: "freemium",
    jobs: ["design", "marketer"],
    why: "Génération et retouche d'image en temps réel — très intuitif.",
    security: 3,
    secNote: "Politique standard, vos images peuvent servir à améliorer le service.",
  },
  {
    name: "Leonardo.AI",
    url: "https://leonardo.ai",
    price: "freemium",
    jobs: ["design", "marketer", "video"],
    why: "150 crédits gratuits/jour, contrôle fin du style.",
    security: 3,
    secNote: "Mode privé sur paliers payants ; gratuit = images publiques.",
  },
  {
    name: "Ideogram",
    url: "https://ideogram.ai",
    price: "freemium",
    jobs: ["design", "marketer"],
    why: "Excellent pour les images contenant du texte (logos, affiches).",
    security: 3,
    secNote: "Images publiques au palier gratuit ; politique claire.",
  },
  {
    name: "Stable Diffusion (local)",
    url: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["design", "photo", "video"],
    why: "100 % gratuit, vos images restent sur votre machine.",
    security: 5,
    secNote: "Open-source, 100 % local — aucune donnée envoyée nulle part.",
  },
  {
    name: "Recraft",
    url: "https://www.recraft.ai",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["design"],
    why: "Génère des illustrations vectorielles éditables.",
    security: 3,
    secNote: "Politique standard, vos créations restent les vôtres.",
  },

  // ---------- Écriture / Journalisme ----------
  {
    name: "DeepL Write",
    url: "https://www.deepl.com/write",
    price: "freemium",
    flags: ["eu"],
    jobs: ["writer", "translator", "student", "lawyer", "hr", "marketer"],
    why: "Améliore vos textes en français — éditeur allemand, RGPD.",
    security: 4,
    secNote: "Éditeur allemand, RGPD natif, textes supprimés après traitement.",
  },
  {
    name: "LanguageTool",
    url: "https://languagetool.org",
    price: "freemium",
    flags: ["eu", "private", "hidden"],
    jobs: ["writer", "student", "translator", "lawyer", "hr"],
    why: "Correcteur grammatical européen, version auto-hébergeable.",
    security: 5,
    secNote: "Open-source, auto-hébergeable, éditeur allemand — RGPD strict.",
  },
  {
    name: "Grammarly",
    url: "https://www.grammarly.com",
    price: "freemium",
    jobs: ["writer", "student", "marketer"],
    why: "Référence pour l'anglais, palier gratuit suffisant.",
    security: 3,
    secNote: "Lit tout ce que vous écrivez ; certifié SOC 2 mais hébergé US.",
  },

  // ---------- Traduction ----------
  {
    name: "DeepL",
    url: "https://www.deepl.com",
    price: "freemium",
    flags: ["eu"],
    jobs: ["translator", "writer", "student", "support", "lawyer"],
    why: "Meilleure qualité française, hébergé en Allemagne.",
    security: 4,
    secNote: "Hébergé en Allemagne, textes supprimés après traduction (palier Pro).",
  },
  {
    name: "LibreTranslate",
    url: "https://libretranslate.com",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["translator", "support"],
    why: "Open-source, installable en local — souverain.",
    security: 5,
    secNote: "Open-source, installable en local : aucune donnée n'est envoyée.",
  },

  // ---------- Recherche / Académique ----------
  {
    name: "Elicit",
    url: "https://elicit.com",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["researcher", "student"],
    why: "Synthétise des articles scientifiques avec citations.",
    security: 3,
    secNote: "Travaille sur articles publics ; vos requêtes restent confidentielles.",
  },
  {
    name: "Consensus",
    url: "https://consensus.app",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["researcher", "student", "doctor"],
    why: "Cherche un consensus dans les études publiées sur un sujet.",
    security: 3,
    secNote: "Sources publiques uniquement, politique claire.",
  },
  {
    name: "Connected Papers",
    url: "https://www.connectedpapers.com",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["researcher", "student"],
    why: "Visualise un graphe d'articles liés à votre publication.",
    security: 4,
    secNote: "Pas de contenu utilisateur sensible — uniquement des références publiques.",
  },

  // ---------- Vidéo ----------
  {
    name: "CapCut",
    url: "https://www.capcut.com",
    price: "freemium",
    jobs: ["video", "marketer"],
    why: "Sous-titres auto, suppression de fond, gratuit et puissant.",
    security: 2,
    secNote: "Édité par ByteDance — collecte large, lisez la politique avant tout usage pro.",
  },
  {
    name: "Descript",
    url: "https://www.descript.com",
    price: "freemium",
    jobs: ["video", "writer"],
    why: "Édite la vidéo en éditant le texte de la transcription.",
    security: 3,
    secNote: "Politique claire, certifié SOC 2 — mais hébergé US.",
  },
  {
    name: "Whisper (local)",
    url: "https://github.com/openai/whisper",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["video", "writer", "researcher", "support"],
    why: "Transcription audio open-source, fonctionne hors-ligne.",
    security: 5,
    secNote: "Open-source, 100 % local — vos audios ne sortent jamais de la machine.",
  },

  // ---------- Photo ----------
  {
    name: "Upscayl",
    url: "https://upscayl.org",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["photo", "design"],
    why: "Agrandit vos photos sans perte, 100 % local et open-source.",
    security: 5,
    secNote: "Open-source, totalement hors-ligne, aucune télémétrie.",
  },
  {
    name: "GFPGAN",
    url: "https://github.com/TencentARC/GFPGAN",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["photo"],
    why: "Restaure les vieux portraits — gratuit, en local.",
    security: 5,
    secNote: "Open-source, exécutable en local — aucune donnée envoyée.",
  },
  {
    name: "Photopea + IA",
    url: "https://www.photopea.com",
    price: "free",
    flags: ["hidden"],
    jobs: ["photo", "design"],
    why: "Photoshop gratuit dans le navigateur, plug-ins IA disponibles.",
    security: 4,
    secNote: "Tout traitement se fait dans votre navigateur, pas d'envoi serveur.",
  },

  // ---------- Audio / Musique ----------
  {
    name: "Suno",
    url: "https://suno.com",
    price: "freemium",
    jobs: ["music", "video", "marketer"],
    why: "Génère des morceaux complets avec voix — gratuit chaque jour.",
    security: 3,
    secNote: "Compositions publiques au palier gratuit ; débats de droits en cours.",
  },
  {
    name: "Udio",
    url: "https://www.udio.com",
    price: "freemium",
    jobs: ["music"],
    why: "Génération musicale très expressive, palier gratuit.",
    security: 3,
    secNote: "Politique standard, créations publiques sans abonnement.",
  },
  {
    name: "AudioCraft (Meta)",
    url: "https://audiocraft.metademolab.com",
    price: "free",
    flags: ["private", "offline", "hidden"],
    jobs: ["music", "video"],
    why: "Open-source, à installer localement — aucune limite.",
    security: 5,
    secNote: "Open-source, exécutable en local — pleine maîtrise.",
  },

  // ---------- Marketing / Sales ----------
  {
    name: "Canva Magic Studio",
    url: "https://www.canva.com/magic-studio/",
    price: "freemium",
    jobs: ["marketer", "design", "artisan"],
    why: "Visuels, textes, présentations — tout-en-un grand public.",
    security: 3,
    secNote: "Politique claire, mais entraînement opt-out à activer.",
  },
  {
    name: "Brevo (ex-Sendinblue)",
    url: "https://www.brevo.com",
    price: "freemium",
    flags: ["eu", "hidden"],
    jobs: ["marketer", "sales", "artisan", "support"],
    why: "Emailing avec IA, éditeur français — RGPD natif.",
    security: 4,
    secNote: "Éditeur français, hébergement UE, RGPD natif.",
  },
  {
    name: "Tactiq",
    url: "https://tactiq.io",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["sales", "pm", "support", "hr"],
    why: "Transcrit et résume vos réunions Meet/Zoom/Teams.",
    security: 3,
    secNote: "Transcription côté client, mais résumés via API tierces — vérifiez les paramètres.",
  },

  // ---------- Données / Tableurs ----------
  {
    name: "Rows",
    url: "https://rows.com",
    price: "freemium",
    flags: ["eu", "hidden"],
    jobs: ["data", "marketer", "finance", "pm"],
    why: "Tableur avec IA intégrée, éditeur portugais.",
    security: 4,
    secNote: "Éditeur portugais (UE), conforme RGPD.",
  },
  {
    name: "Julius",
    url: "https://julius.ai",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["data", "researcher", "finance"],
    why: "Analyse de données par conversation, génère graphes et code.",
    security: 3,
    secNote: "Vos données sont envoyées au service — pas idéal pour données sensibles.",
  },

  // ---------- Juridique ----------
  {
    name: "Doctrine",
    url: "https://www.doctrine.fr",
    price: "cheap",
    flags: ["eu", "hidden"],
    jobs: ["lawyer"],
    why: "Recherche juridique française, IA pour synthétiser jurisprudence.",
    security: 4,
    secNote: "Éditeur français, hébergement UE, conforme aux règles du barreau.",
  },
  {
    name: "Lexnow",
    url: "https://www.lexnow.io",
    price: "freemium",
    flags: ["eu", "hidden"],
    jobs: ["lawyer"],
    why: "Assistant juridique français — vérifiez toujours les sources.",
    security: 4,
    secNote: "Acteur français, hébergement UE — vérifiez la politique pour le secret pro.",
  },

  // ---------- RH ----------
  {
    name: "Teal",
    url: "https://www.tealhq.com",
    price: "freemium",
    flags: ["hidden"],
    jobs: ["hr", "student"],
    why: "Optimise CV et lettres de motivation, palier gratuit utile.",
    security: 3,
    secNote: "Politique claire, mais vos CV transitent sur leurs serveurs.",
  },

  // ---------- Santé (prudence) ----------
  {
    name: "OpenEvidence",
    url: "https://www.openevidence.com",
    price: "free",
    flags: ["hidden"],
    jobs: ["doctor"],
    why: "Réservé aux pros de santé — répond avec des sources médicales vérifiées.",
    security: 4,
    secNote: "Réservé aux pros vérifiés, sources publiques — ne pas y entrer de données patient.",
  },
];
